# Wallust template for Starship.toml
# Place this in ~/.config/wallust/templates/starship.toml

format = """
[](#4A4B51)\
$os\
$username\
[](bg:#1B2E4F fg:#4A4B51)\
$directory\
[](fg:#1B2E4F bg:#1B2F50)\
$git_branch\
$git_status\
[](fg:#1B2F50 bg:#1D3051)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#1D3051 bg:#7882BB)\
$docker_context\
[](fg:#7882BB bg:#868ABA)\
$time\
[ ](fg:#868ABA)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#4A4B51"
style_root = "bg:#4A4B51"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#4A4B51"
disabled = true # Disabled by default

[directory]
style = "bg:#1B2E4F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#7882BB"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#1B2F50"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#1B2F50"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#1D3051"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#868ABA"
format = '[ ♥ $time ]($style)'
