# Wallust template for Starship.toml
# Place this in ~/.config/wallust/templates/starship.toml

format = """
[](#55535D)\
$os\
$username\
[](bg:#343163 fg:#55535D)\
$directory\
[](fg:#343163 bg:#574C84)\
$git_branch\
$git_status\
[](fg:#574C84 bg:#565889)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#565889 bg:#836CA4)\
$docker_context\
[](fg:#836CA4 bg:#B58CCB)\
$time\
[ ](fg:#B58CCB)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#55535D"
style_root = "bg:#55535D"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#55535D"
disabled = true # Disabled by default

[directory]
style = "bg:#343163"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#836CA4"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#574C84"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#574C84"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#565889"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#B58CCB"
format = '[ ♥ $time ]($style)'
